# El puerto donde correrá el API REST
server.port=8080
server.address=0.0.0.0

# --- Base de Datos PostgreSQL ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# --- Configuración MQTT ---
mqtt.broker.url=ssl://118c4eb634124e6a914d87e18ad2ea02.s1.eu.hivemq.cloud:8883
mqtt.topic=pavewatch/alertas

# Credenciales de acceso
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}

# Esto le dice al ORM que imprima en la consola el SQL que acaba de fabricar y tambien mostrar el debug
spring.jpa.show-sql=true

# Esto hace que el SQL se imprima ordenado con saltos de línea (ideal para exponer)
spring.jpa.properties.hibernate.format_sql=true